# Generated by Django 5.2.9 on 2025-12-10 19:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllFilms',
            fields=[
                ('film_id', models.AutoField(db_column='Film_id', primary_key=True, serialize=False)),
                ('film_name', models.CharField(db_column='Film_name', max_length=255)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
            ],
            options={
                'db_table': 'All_Films',
            },
        ),
        migrations.CreateModel(
            name='AllShows',
            fields=[
                ('show_id', models.AutoField(db_column='Show_id', primary_key=True, serialize=False)),
                ('show_name', models.CharField(db_column='Show_name', max_length=255)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
                ('rating', models.DecimalField(blank=True, db_column='rating', decimal_places=2, max_digits=3, null=True)),
                ('years', models.CharField(blank=True, db_column='Years', max_length=50, null=True)),
            ],
            options={
                'db_table': 'All_shows',
            },
        ),
        migrations.CreateModel(
            name='AllTables',
            fields=[
                ('table_id', models.AutoField(db_column='Table_id', primary_key=True, serialize=False)),
                ('table_name', models.CharField(db_column='Table_name', max_length=255)),
            ],
            options={
                'db_table': 'All_tables',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('table_id', models.AutoField(db_column='Table_id', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, db_column='date')),
                ('changes_to_data', models.TextField(db_column='changes_to_data')),
            ],
            options={
                'db_table': 'Audit_log',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('director_id', models.AutoField(db_column='Director_id', primary_key=True, serialize=False)),
                ('director_name', models.CharField(db_column='Director_name', max_length=255)),
            ],
            options={
                'db_table': 'Movie_Directors',
            },
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('genre_id', models.AutoField(db_column='Genre_id', primary_key=True, serialize=False)),
                ('genre_name', models.CharField(db_column='Genre_name', max_length=100)),
            ],
            options={
                'db_table': 'Movie_Genre',
            },
        ),
        migrations.CreateModel(
            name='MovieLanguage',
            fields=[
                ('language_id', models.AutoField(db_column='Language_id', primary_key=True, serialize=False)),
                ('language_name', models.CharField(db_column='Language_name', max_length=100)),
            ],
            options={
                'db_table': 'Movie_Language',
            },
        ),
        migrations.CreateModel(
            name='ShowCertificate',
            fields=[
                ('cert_id', models.AutoField(db_column='cert_id', primary_key=True, serialize=False)),
                ('cert_rating', models.CharField(db_column='cert_rating', max_length=20)),
            ],
            options={
                'db_table': 'Show_certificate',
            },
        ),
        migrations.CreateModel(
            name='ShowGenre',
            fields=[
                ('genre_id', models.AutoField(db_column='genre_id', primary_key=True, serialize=False)),
                ('genre_name', models.CharField(db_column='genre_name', max_length=100)),
            ],
            options={
                'db_table': 'Show_genre',
            },
        ),
        migrations.CreateModel(
            name='MovieAverageRating',
            fields=[
                ('film_name', models.CharField(db_column='Film_name', max_length=255)),
                ('film_id', models.OneToOneField(db_column='Film_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.allfilms')),
                ('average_score', models.DecimalField(db_column='Average_score', decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'Movie_Average_rating',
            },
        ),
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('actor_id', models.AutoField(db_column='Actor_id', primary_key=True, serialize=False)),
                ('actor_name', models.CharField(db_column='Actor_name', max_length=255)),
                ('film_id', models.ForeignKey(blank=True, db_column='film_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.allfilms')),
            ],
            options={
                'db_table': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='ShowAverageRating',
            fields=[
                ('show_name', models.CharField(db_column='Film_name', max_length=255)),
                ('show_id', models.OneToOneField(db_column='Film_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.allshows')),
                ('average_score', models.DecimalField(db_column='Average_score', decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'Show_average_rating',
            },
        ),
        migrations.AddField(
            model_name='allfilms',
            name='director_id',
            field=models.ForeignKey(db_column='Director_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.moviedirector'),
        ),
        migrations.AddField(
            model_name='allfilms',
            name='genre_id',
            field=models.ForeignKey(db_column='Genre_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.moviegenre'),
        ),
        migrations.AddField(
            model_name='allfilms',
            name='language_id',
            field=models.ForeignKey(db_column='Language_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.movielanguage'),
        ),
        migrations.CreateModel(
            name='PreviousSearches',
            fields=[
                ('search_id', models.AutoField(db_column='Search_id', primary_key=True, serialize=False)),
                ('director_id', models.ForeignKey(blank=True, db_column='Director_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.moviedirector')),
                ('film_id', models.ForeignKey(blank=True, db_column='Film_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.allfilms')),
                ('user_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Previous_Searches',
            },
        ),
        migrations.AddField(
            model_name='allshows',
            name='cert_id',
            field=models.ForeignKey(db_column='Cert_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.showcertificate'),
        ),
        migrations.AddField(
            model_name='allshows',
            name='genre_id',
            field=models.ForeignKey(db_column='Genre_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.showgenre'),
        ),
        migrations.CreateModel(
            name='ActedIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(db_column='Actor_name', max_length=255)),
                ('actor_id', models.ForeignKey(db_column='Actor_id', on_delete=django.db.models.deletion.CASCADE, to='api.actors')),
                ('show_id', models.ForeignKey(db_column='Show_id', on_delete=django.db.models.deletion.CASCADE, to='api.allshows')),
            ],
            options={
                'db_table': 'Acted_in',
                'unique_together': {('show_id', 'actor_id')},
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('user_id', models.OneToOneField(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.user')),
                ('fav_actor', models.CharField(blank=True, db_column='Fav_actor', max_length=255, null=True)),
                ('fav_decade', models.CharField(blank=True, db_column='Fav_decade', max_length=20, null=True)),
                ('fav_director', models.ForeignKey(blank=True, db_column='Fav_director', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.moviedirector')),
                ('fav_genre', models.ForeignKey(blank=True, db_column='Fav_genre', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.moviegenre')),
            ],
            options={
                'db_table': 'Favorites',
            },
        ),
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField(db_column='User_rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('user_review', models.TextField(blank=True, db_column='User_review', null=True)),
                ('film_id', models.ForeignKey(db_column='Film_id', on_delete=django.db.models.deletion.CASCADE, to='api.allfilms')),
                ('user_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Movie_rating',
                'unique_together': {('film_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='ShowUserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField(db_column='User_rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('user_review', models.TextField(blank=True, db_column='User_review', null=True)),
                ('show_id', models.ForeignKey(db_column='Show_id', on_delete=django.db.models.deletion.CASCADE, to='api.allshows')),
                ('user_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Show_user_rating',
                'unique_together': {('show_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='WatchedMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.ForeignKey(db_column='Film_id', on_delete=django.db.models.deletion.CASCADE, to='api.allfilms')),
                ('user_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Watched_movie',
                'unique_together': {('film_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='WatchedShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.ForeignKey(db_column='Show_id', on_delete=django.db.models.deletion.CASCADE, to='api.allshows')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Watched_show',
                'unique_together': {('show_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='WatchLaterMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.ForeignKey(db_column='Film_id', on_delete=django.db.models.deletion.CASCADE, to='api.allfilms')),
                ('user_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Watch_later_movie',
                'unique_together': {('film_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='WatchLaterShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.ForeignKey(db_column='Show_id', on_delete=django.db.models.deletion.CASCADE, to='api.allshows')),
                ('user_id', models.ForeignKey(db_column='User_id', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'db_table': 'Watch_later_show',
                'unique_together': {('show_id', 'user_id')},
            },
        ),
    ]
